name: trackyourflights
description: A new Flutter project.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.17.0-266.7.beta <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_riverpod: ^1.0.3
  rxdart: ^0.27.3
  hooks_riverpod: ^1.0.3
  flutter_hooks: ^0.18.3
  riverpod: ^1.0.3
  meta: ^1.7.0
  state_notifier: ^0.7.2+1
  intl: ^0.17.0
  http: ^0.13.4
  shared_preferences: ^2.0.13
  collection: ^1.16.0
  uuid: ^3.0.6
  lottie: ^1.3.0
  url_launcher: ^6.1.0
  flutter_map: ^0.14.0
  latlong2: ^0.8.1
  mapbox_gl: ^0.15.0
  equatable: ^2.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/